# Weapon dictionary
weapons = {
    "Dagger": {
        "cost": 25,
        "attack_bonus": 1,
        "melee": True,
        "ranged": False,
        "diagonal": False,
        "thrown": True,
        "two_handed": False,
        "wizard_ok": True,
        "stackable": True,
        "min_range": 0,
    },
    "Staff": {
        "cost": 100,
        "attack_bonus": 2,
        "melee": True,
        "ranged": False,
        "diagonal": True,
        "thrown": False,
        "two_handed": True,
        "wizard_ok": True,
        "stackable": False,
        "min_range": 0,
    },
    "Shortsword": {
        "cost": 150,
        "attack_bonus": 2,
        "melee": True,
        "ranged": False,
        "diagonal": False,
        "thrown": False,
        "two_handed": False,
        "wizard_ok": False,
        "stackable": False,
        "min_range": 0,
    },
    "Hand Axe": {
        "cost": 150,
        "attack_bonus": 2,
        "melee": True,
        "ranged": False,
        "diagonal": False,
        "thrown": True,
        "two_handed": False,
        "wizard_ok": False,
        "stackable": True,
        "min_range": 0,
    },
    "Broadsword": {
        "cost": 250,
        "attack_bonus": 3,
        "melee": True,
        "ranged": False,
        "diagonal": False,
        "thrown": False,
        "two_handed": False,
        "wizard_ok": False,
        "stackable": False,
        "min_range": 0,
    },
    "Longsword": {
        "cost": 350,
        "attack_bonus": 3,
        "melee": True,
        "ranged": False,
        "diagonal": True,
        "thrown": False,
        "two_handed": False,
        "wizard_ok": False,
        "stackable": False,
        "min_range": 0,
    },
    "Crossbow": {
        "cost": 350,
        "attack_bonus": 3,
        "melee": False,
        "ranged": True,
        "diagonal": False,
        "thrown": False,
        "two_handed": False,
        "wizard_ok": False,
        "stackable": False,
        "min_range": 2,
    },
    "Battle Axe": {
        "cost": 450,
        "attack_bonus": 4,
        "melee": True,
        "ranged": False,
        "diagonal": False,
        "thrown": False,
        "two_handed": True,
        "wizard_ok": False,
        "stackable": False,
        "min_range": 0,
    },
    "Unarmed": {
        "cost": 0,
        "attack_bonus": 1,
        "melee": True,
        "ranged": False,
        "diagonal": False,
        "thrown": False,
        "two_handed": False,
        "wizard_ok": True,
        "stackable": False,
        "min_range": 0,
    },
}

# Armour Dictionary
armour = {
    "Helmet": {
        "cost": 125,
        "defence_bonus": 1,
        "wizard_ok": False,
        "is_body_armour": False,
        "is_off_hand": False,
        "move_penalty": 0,
        "slot": "head",
    },
    "Shield": {
        "cost": 150,
        "defence_bonus": 1,
        "wizard_ok": False,
        "is_body_armour": False,
        "is_off_hand": True,
        "move_penalty": 0,
        "slot": "off_hand",
    },
    "Bracers": {
        "cost": 200,
        "defence_bonus": 1,
        "wizard_ok": True,
        "is_body_armour": False,
        "is_off_hand": False,
        "move_penalty": 0,
        "slot": "arm",
    },
    "Chain Mail": {
        "cost": 500,
        "defence_bonus": 1,
        "wizard_ok": False,
        "is_body_armour": True,
        "is_off_hand": False,
        "move_penalty": 0,
        "slot": "body",
    },
    "Plate Mail": {
        "cost": 850,
        "defence_bonus": 2,
        "wizard_ok": False,
        "is_body_armour": True,
        "is_off_hand": False,
        "move_penalty": 1,
        "slot": "body",
    },
    "Empty": {
        "cost": 0,
        "defence_bonus": 0,
        "wizard_ok": True,
        "is_body_armour": False,
        "is_off_hand": False,
        "move_penalty": 0,
        "slot": None,
    },
}
